/**
 * Redux action types
 */

export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";
export const GET_INGREDIENTS_START = "GET_INGREDIENTS_START";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";
export const GET_MEALS_START = "GET_MEALS_START";
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const GET_MEALS_ERROR = "GET_MEALS_ERROR";
export const GET_MEAL_DETAIL_START = "GET_MEAL_DETAIL_START";
export const GET_MEAL_DETAIL_SUCCESS = "GET_MEAL_DETAIL_SUCCESS";
export const GET_MEAL_DETAIL_ERROR = "GET_MEAL_DETAIL_ERROR";
export const SAVE_CURRENT_MEAL = "SAVE_CURRENT_MEAL";